#!/usr/bin/env python
# coding: utf-8

# In[26]:


#1
#def moriintoo(n):
#    n=int(input())
#    a=1
#    while a<n+1:
#        print('*'*a)
#        a+=1
#moriintoo(1)

#2
#def moriintoo_list(n):
#    n=int(input())
#    a=1
#    while a<n+1:
#        print(['*'*a])
#        a+=1
#moriintoo_list(1)

#3
#def ihbaga_key(students):
#    a= max(students, key=students.get)
#    b= min(students, key=students.get)
#    return a,b
#students = {'Bat': 18,'Oyun': 22,'Dulam': 21,'Suren':20}
#ihbaga_key(students)

#4
#import numpy as np
#x=np.arange(1,1000)
#z=0
#for i in x:
#    if i%3==0 or i%7==0:
#        z=z+i
#print(z)
